sudo: false
language: python

python:
#  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
 - "pip install -r requirements-dev.txt"
 - pip install codecov
 - python setup.py build
 - python setup.py install

# - "pip install tox-travis"

script:
- py.test --cov postcard_creator

#script: tox

#install:


after_success:
  - codecov